// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file HelloWorld.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _HelloWorld_H_
#define _HelloWorld_H_

#include <micrortps/client/core/session/session.h>

/*!
 * @brief This struct represents the structure HelloWorld defined by the user in the IDL file.
 * @ingroup HELLOWORLD
 */
typedef struct HelloWorld
{
    uint32_t index;
    char* message;

} HelloWorld;

bool serialize_HelloWorld_topic(MicroBuffer* writer, const HelloWorld* topic);
bool deserialize_HelloWorld_topic(MicroBuffer* reader, HelloWorld* topic);
uint32_t size_of_HelloWorld_topic(const HelloWorld* topic, uint32_t size);
bool write_HelloWorld_topic(Session* session, StreamId stream_id, mrObjectId datawriter_id, HelloWorld* topic);

#endif // _HelloWorld_H_
