// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file HelloWorld.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "HelloWorld.h"

#include <microcdr/microcdr.h>
#include <string.h>

bool serialize_HelloWorld_topic(MicroBuffer* writer, const HelloWorld* topic)
{
    serialize_uint32_t(writer, topic->index);
    serialize_sequence_char(writer, topic->message, (uint32_t)strlen(topic->message) + 1);

    return writer->error == BUFFER_OK;
}

bool deserialize_HelloWorld_topic(MicroBuffer* reader, HelloWorld* topic)
{
    deserialize_uint32_t(reader, &topic->index);
    uint32_t size_message;
    deserialize_sequence_char(reader, topic->message, &size_message);

    return reader->error == BUFFER_OK;
}

uint32_t size_of_HelloWorld_topic(const HelloWorld* topic, uint32_t size)
{
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4) + (uint32_t)strlen(topic->message) + 1;

    return size;
}