// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ShapeType.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "ShapeType.h"

#include <microcdr/microcdr.h>
#include <string.h>

bool ShapeType_serialize_topic(MicroBuffer* writer, const ShapeType* topic)
{
    (void) serialize_sequence_char(writer, topic->color, (uint32_t)strlen(topic->color) + 1);
    (void) serialize_int32_t(writer, topic->x);
    (void) serialize_int32_t(writer, topic->y);
    (void) serialize_int32_t(writer, topic->shapesize);

    return writer->error == BUFFER_OK;
}

bool ShapeType_deserialize_topic(MicroBuffer* reader, ShapeType* topic)
{
    uint32_t size_color;
    (void) deserialize_sequence_char(reader, topic->color, &size_color);
    (void) deserialize_int32_t(reader, &topic->x);
    (void) deserialize_int32_t(reader, &topic->y);
    (void) deserialize_int32_t(reader, &topic->shapesize);

    return reader->error == BUFFER_OK;
}

uint32_t ShapeType_size_of_topic(const ShapeType* topic, uint32_t size)
{
    size += 4 + get_alignment(size, 4) + (uint32_t)strlen(topic->color) + 1;
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);
    size += 4 + get_alignment(size, 4);

    return size;
}