// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file WriteShapeType.h
 * This header file contains the write function of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _WRITE_ShapeType_H_
#define _WRITE_ShapeType_H_

#include "ShapeType.h"

#include <micrortps/client/client.h>

bool mr_write_ShapeType_topic(mrSession* session, mrStreamId stream_id, mrObjectId datawriter_id, ShapeType* topic);

#endif // _WRITE_ShapeType_H_
