struct TestType {
    float               test_float;
    double              test_double;
    short               test_short;
    long                test_long;
    long long           test_long_long;
    unsigned short      test_unsigned_short;
    unsigned long       test_unsigned_long;
    unsigned long long  test_unsigned_long_long;
    char                test_char;
    boolean             test_boolean;
    octet               test_octet; 
    string              test_string;
};
