// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file HelloWorld.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _HelloWorld_H_
#define _HelloWorld_H_

#include <string.h>
#include <stdlib.h>
#include <micrortps/client/client.h>
#include <microcdr/microcdr.h>

/*!
 * @brief This class represents the structure HelloWorld defined by the user in the IDL file.
 * @ingroup HELLOWORLD
 */
typedef struct HelloWorld
{
    uint32_t index;
    char* message;
} HelloWorld;

bool serialize_HelloWorld_topic(MicroBuffer* writer, const AbstractTopic* topic_structure)
{
    HelloWorld* topic = (HelloWorld*) topic_structure->topic;
    serialize_uint32_t(writer, topic->index);
    serialize_uint32_t(writer, strlen(topic->message) + 1);
    serialize_array_char(writer, topic->message, strlen(topic->message) + 1);

    return true;
}

HelloWorld *deserialize_HelloWorld_message(MicroBuffer *message)
{
    HelloWorld* topic = malloc(sizeof(HelloWorld));
    deserialize_uint32_t(message, &topic->index);
    uint32_t size_message = 0;
    deserialize_uint32_t(message, &size_message);
    topic->message = malloc(size_message);
    deserialize_array_char(message, topic->message, size_message);

    return topic;
}

void deallocate_HelloWorld_topic(HelloWorld *topic)
{
    free(topic->message);
    free(topic);
}

#endif // _HelloWorld_H_