// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Imu.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _Imu_H_
#define _Imu_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/*!
 * @brief This struct represents the structure SensorMsgImu defined by the user in the IDL file.
 * @ingroup IMU
 */
typedef struct SensorMsgImu
{
    int32_t sec;
    uint32_t index;
    char frame_id[255];

    double orientation_x;
    double orientation_y;
    double orientation_z;
    double orientation_w;
    double orientation_covariance[9];
    double angular_velocity_x;
    double angular_velocity_y;
    double angular_velocity_z;
    double angular_velocity_w;
    double angular_velocity_covariance[9];
    double linear_acceleration_x;
    double linear_acceleration_y;
    double linear_acceleration_z;
    double linear_acceleration_w;
    double linear_acceleration_covariance[9];
} SensorMsgImu;

struct ucdrBuffer;

bool SensorMsgImu_serialize_topic(struct ucdrBuffer* writer, const SensorMsgImu* topic);
bool SensorMsgImu_deserialize_topic(struct ucdrBuffer* reader, SensorMsgImu* topic);
uint32_t SensorMsgImu_size_of_topic(const SensorMsgImu* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _Imu_H_