// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Imu.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "Imu.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool SensorMsgImu_serialize_topic(ucdrBuffer* writer, const SensorMsgImu* topic)
{
    (void) ucdr_serialize_int32_t(writer, topic->sec);

    (void) ucdr_serialize_uint32_t(writer, topic->index);

    (void) ucdr_serialize_string(writer, topic->frame_id);

    (void) ucdr_serialize_double(writer, topic->orientation_x);

    (void) ucdr_serialize_double(writer, topic->orientation_y);

    (void) ucdr_serialize_double(writer, topic->orientation_z);

    (void) ucdr_serialize_double(writer, topic->orientation_w);

    (void) ucdr_serialize_array_double(writer, topic->orientation_covariance, sizeof(topic->orientation_covariance) / sizeof(double));

    (void) ucdr_serialize_double(writer, topic->angular_velocity_x);

    (void) ucdr_serialize_double(writer, topic->angular_velocity_y);

    (void) ucdr_serialize_double(writer, topic->angular_velocity_z);

    (void) ucdr_serialize_double(writer, topic->angular_velocity_w);

    (void) ucdr_serialize_array_double(writer, topic->angular_velocity_covariance, sizeof(topic->angular_velocity_covariance) / sizeof(double));

    (void) ucdr_serialize_double(writer, topic->linear_acceleration_x);

    (void) ucdr_serialize_double(writer, topic->linear_acceleration_y);

    (void) ucdr_serialize_double(writer, topic->linear_acceleration_z);

    (void) ucdr_serialize_double(writer, topic->linear_acceleration_w);

    (void) ucdr_serialize_array_double(writer, topic->linear_acceleration_covariance, sizeof(topic->linear_acceleration_covariance) / sizeof(double));

    return !writer->error;
}

bool SensorMsgImu_deserialize_topic(ucdrBuffer* reader, SensorMsgImu* topic)
{
    (void) ucdr_deserialize_int32_t(reader, &topic->sec);

    (void) ucdr_deserialize_uint32_t(reader, &topic->index);

    (void) ucdr_deserialize_string(reader, topic->frame_id, 255);

    (void) ucdr_deserialize_double(reader, &topic->orientation_x);

    (void) ucdr_deserialize_double(reader, &topic->orientation_y);

    (void) ucdr_deserialize_double(reader, &topic->orientation_z);

    (void) ucdr_deserialize_double(reader, &topic->orientation_w);

    (void) ucdr_deserialize_array_double(reader, topic->orientation_covariance, sizeof(topic->orientation_covariance) / sizeof(double));

    (void) ucdr_deserialize_double(reader, &topic->angular_velocity_x);

    (void) ucdr_deserialize_double(reader, &topic->angular_velocity_y);

    (void) ucdr_deserialize_double(reader, &topic->angular_velocity_z);

    (void) ucdr_deserialize_double(reader, &topic->angular_velocity_w);

    (void) ucdr_deserialize_array_double(reader, topic->angular_velocity_covariance, sizeof(topic->angular_velocity_covariance) / sizeof(double));

    (void) ucdr_deserialize_double(reader, &topic->linear_acceleration_x);

    (void) ucdr_deserialize_double(reader, &topic->linear_acceleration_y);

    (void) ucdr_deserialize_double(reader, &topic->linear_acceleration_z);

    (void) ucdr_deserialize_double(reader, &topic->linear_acceleration_w);

    (void) ucdr_deserialize_array_double(reader, topic->linear_acceleration_covariance, sizeof(topic->linear_acceleration_covariance) / sizeof(double));

    return !reader->error;
}

uint32_t SensorMsgImu_size_of_topic(const SensorMsgImu* topic, uint32_t size)
{
    uint32_t previousSize = size;
    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->frame_id) + 1;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + sizeof(topic->orientation_covariance);

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + sizeof(topic->angular_velocity_covariance);

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + 8;

    size += ucdr_alignment(size, 8) + sizeof(topic->linear_acceleration_covariance);

    return size - previousSize;
}
