// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ImuPublisher.c
 * Publisher example.
 *
 * This file was generated by the tool microxrceddsgen.
 */

#include "Imu.h"

#include <uxr/client/client.h>
#include <ucdr/microcdr.h>

#include <stdio.h>
#include <string.h>

#define STREAM_HISTORY  8
#define BUFFER_SIZE     UXR_CONFIG_UDP_TRANSPORT_MTU * STREAM_HISTORY


const char* participant_xml = "<dds>"
                                  "<participant>"
                                      "<rtps>"
                                          "<name>default_xrce_participant</name>"
                                      "</rtps>"
                                  "</participant>"
                              "</dds>";
const char* topic_xml = "<dds>"
                            "<topic>"
                                "<name>ImuPubSubTopic</name>"
                                "<dataType>SensorMsgImu</dataType>"
                            "</topic>"
                        "</dds>";
const char* publisher_xml = "";
const char* datawriter_xml = "<dds>"
                                 "<data_writer>"
                                     "<topic>"
                                         "<kind>NO_KEY</kind>"
                                         "<name>ImuPubSubTopic</name>"
                                         "<dataType>SensorMsgImu</dataType>"
                                     "</topic>"
                                 "</data_writer>"
                             "</dds>";

int main(void)
{
    // Transport
    uxrUDPTransport transport;
    uxrUDPPlatform udp_platform;
    if(!uxr_init_udp_transport(&transport, &udp_platform, "127.0.0.1", 2018))
    {
        printf("Error at create transport.\n");
        return 1;
    }

    // Session
    uxrSession session;
    uxr_init_session(&session, &transport.comm, 0xAAAABBBB);
    if(!uxr_create_session(&session))
    {
        printf("Error at create session.\n");
        return 1;
    }

    // Streams
    uint8_t output_reliable_stream_buffer[BUFFER_SIZE];
    uxrStreamId reliable_out = uxr_create_output_reliable_stream(&session, output_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    uint8_t input_reliable_stream_buffer[BUFFER_SIZE];
    uxr_create_input_reliable_stream(&session, input_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    // Create entities
    uxrObjectId participant_id = uxr_object_id(0x01, UXR_PARTICIPANT_ID);
    uint16_t participant_req = uxr_buffer_create_participant_xml(&session, reliable_out, participant_id, 0, participant_xml, UXR_REPLACE);

    uxrObjectId topic_id = uxr_object_id(0x01, UXR_TOPIC_ID);
    uint16_t topic_req = uxr_buffer_create_topic_xml(&session, reliable_out, topic_id, participant_id, topic_xml, UXR_REPLACE);

    uxrObjectId publisher_id = uxr_object_id(0x01, UXR_PUBLISHER_ID);
    uint16_t publisher_req = uxr_buffer_create_publisher_xml(&session, reliable_out, publisher_id, participant_id, publisher_xml, UXR_REPLACE);

    uxrObjectId datawriter_id = uxr_object_id(0x01, UXR_DATAWRITER_ID);
    uint16_t datawriter_req = uxr_buffer_create_datawriter_xml(&session, reliable_out, datawriter_id, publisher_id, datawriter_xml, UXR_REPLACE);

    // Send create entities message and wait its status
    uint8_t status[4];
    uint16_t requests[4] = {participant_req, topic_req, publisher_req, datawriter_req};
    if(!uxr_run_session_until_all_status(&session, 1000, requests, status, 4))
    {
        printf("Error at create entities: participant: %i topic: %i publisher: %i darawriter: %i\n", status[0], status[1], status[2], status[3]);
        return 1;
    }

    SensorMsgImu topic = {0};
    topic.sec = 1;
    topic.index = 2;
    strcpy(topic.frame_id, "eProsima");

    topic.orientation_x = 0.3;
    topic.orientation_y = 0.4;
    topic.orientation_z = 0.5;
    topic.orientation_w = 0.6;

    topic.orientation_covariance[0] = 0.7;
    topic.orientation_covariance[1] = 0.8;
    topic.orientation_covariance[2] = 0.9;
    topic.orientation_covariance[3] = 1.0;
    topic.orientation_covariance[4] = 1.1;
    topic.orientation_covariance[5] = 1.2;
    topic.orientation_covariance[6] = 1.3;
    topic.orientation_covariance[7] = 1.4;
    topic.orientation_covariance[8] = 1.5;

    topic.angular_velocity_x = 0.3 + 2.0;
    topic.angular_velocity_y = 0.4 + 2.0;
    topic.angular_velocity_z = 0.5 + 2.0;
    topic.angular_velocity_w = 0.6 + 2.0;

    topic.angular_velocity_covariance[0] = 0.7 + 2.0;
    topic.angular_velocity_covariance[1] = 0.8 + 2.0;
    topic.angular_velocity_covariance[2] = 0.9 + 2.0;
    topic.angular_velocity_covariance[3] = 1.0 + 2.0;
    topic.angular_velocity_covariance[4] = 1.1 + 2.0;
    topic.angular_velocity_covariance[5] = 1.2 + 2.0;
    topic.angular_velocity_covariance[6] = 1.3 + 2.0;
    topic.angular_velocity_covariance[7] = 1.4 + 2.0;
    topic.angular_velocity_covariance[8] = 1.5 + 2.0;

    topic.linear_acceleration_x = 0.3 + 4.0;
    topic.linear_acceleration_y = 0.4 + 4.0;
    topic.linear_acceleration_z = 0.5 + 4.0;
    topic.linear_acceleration_w = 0.6 + 4.0;

    topic.linear_acceleration_covariance[0] = 0.7 + 4.0;
    topic.linear_acceleration_covariance[1] = 0.8 + 4.0;
    topic.linear_acceleration_covariance[2] = 0.9 + 4.0;
    topic.linear_acceleration_covariance[3] = 1.0 + 4.0;
    topic.linear_acceleration_covariance[4] = 1.1 + 4.0;
    topic.linear_acceleration_covariance[5] = 1.2 + 4.0;
    topic.linear_acceleration_covariance[6] = 1.3 + 4.0;
    topic.linear_acceleration_covariance[7] = 1.4 + 4.0;
    topic.linear_acceleration_covariance[8] = 1.5 + 4.0;

    // Write topics
    while(true)
    {
        ucdrBuffer mb;
        uint32_t topic_size = SensorMsgImu_size_of_topic(&topic, 0);
        uxr_prepare_output_stream(&session, reliable_out, datawriter_id, &mb, topic_size);
        SensorMsgImu_serialize_topic(&mb, &topic);

        //send and wait one second
        uxr_run_session_time(&session, 1000);
    }

    // Delete resources
    uxr_delete_session(&session);

    return 0;
}
