// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ImuSubscriber.c
 * Subscriber example.
 *
 * This file was generated by the tool microxrceddsgen.
 */

#include "Imu.h"
#include <uxr/client/client.h>
#include <stdio.h>

#define STREAM_HISTORY  8
#define BUFFER_SIZE     UXR_CONFIG_UDP_TRANSPORT_MTU * STREAM_HISTORY


const char* participant_xml = "<dds>"
                                  "<participant>"
                                      "<rtps>"
                                          "<name>default_xrce_participant</name>"
                                      "</rtps>"
                                  "</participant>"
                              "</dds>";
const char* topic_xml = "<dds>"
                            "<topic>"
                                "<name>ImuPubSubTopic</name>"
                                "<dataType>SensorMsgImu</dataType>"
                            "</topic>"
                        "</dds>";
const char* subscriber_xml = "";
const char* datareader_xml = "<dds>"
                                 "<data_reader>"
                                     "<topic>"
                                         "<kind>NO_KEY</kind>"
                                         "<name>ImuPubSubTopic</name>"
                                         "<dataType>SensorMsgImu</dataType>"
                                     "</topic>"
                                 "</data_reader>"
                             "</dds>";

void on_topic(uxrSession* session, uxrObjectId object_id, uint16_t request_id, uxrStreamId stream_id, struct ucdrBuffer* mb, void* args)
{
    (void) session; (void) object_id; (void) request_id; (void) stream_id; (void) args;

    SensorMsgImu topic;
    SensorMsgImu_deserialize_topic(mb, &topic);

    printf("sec: %d\n", topic.sec);
    printf("nsec: %d\n", topic.index);
    printf("frame_id: %s\n", topic.frame_id);

    printf("orientation X: %f\n", topic.orientation_x);
    printf("orientation Y: %f\n", topic.orientation_y);
    printf("orientation Z: %f\n", topic.orientation_z);
    printf("orientation W: %f\n", topic.orientation_w);

    printf("orientation variance: [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f]\n",
           topic.orientation_covariance[0],
           topic.orientation_covariance[1],
           topic.orientation_covariance[2],
           topic.orientation_covariance[3],
           topic.orientation_covariance[4],
           topic.orientation_covariance[5],
           topic.orientation_covariance[6],
           topic.orientation_covariance[7],
           topic.orientation_covariance[8]);

    printf("angular velocity X: %f\n", topic.angular_velocity_x);
    printf("angular velocity Y: %f\n", topic.angular_velocity_y);
    printf("angular velocity Z: %f\n", topic.angular_velocity_z);
    printf("angular velocity W: %f\n", topic.angular_velocity_w);

    printf("angular velocity variance: [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f]\n",
           topic.angular_velocity_covariance[0],
           topic.angular_velocity_covariance[1],
           topic.angular_velocity_covariance[2],
           topic.angular_velocity_covariance[3],
           topic.angular_velocity_covariance[4],
           topic.angular_velocity_covariance[5],
           topic.angular_velocity_covariance[6],
           topic.angular_velocity_covariance[7],
           topic.angular_velocity_covariance[8]);

    printf("linear acceleration X: %f\n", topic.linear_acceleration_x);
    printf("linear acceleration Y: %f\n", topic.linear_acceleration_y);
    printf("linear acceleration Z: %f\n", topic.linear_acceleration_z);
    printf("linear acceleration W: %f\n", topic.linear_acceleration_w);

    printf("linear acceleration variance: [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f], [%f]\n",
           topic.linear_acceleration_covariance[0],
           topic.linear_acceleration_covariance[1],
           topic.linear_acceleration_covariance[2],
           topic.linear_acceleration_covariance[3],
           topic.linear_acceleration_covariance[4],
           topic.linear_acceleration_covariance[5],
           topic.linear_acceleration_covariance[6],
           topic.linear_acceleration_covariance[7],
           topic.linear_acceleration_covariance[8]);
}

int main(void)
{
    // Transport
    uxrUDPTransport transport;
    uxrUDPPlatform udp_platform;
    if(!uxr_init_udp_transport(&transport, &udp_platform, "127.0.0.1", 2018))
    {
        printf("Error at create transport.\n");
        return 1;
    }

    // Session
    uxrSession session;
    uxr_init_session(&session, &transport.comm, 0xCCCCDDDD);
    uxr_set_topic_callback(&session, on_topic, NULL);
    if(!uxr_create_session(&session))
    {
        printf("Error at create session.\n");
        return 1;
    }

    // Streams
    uint8_t output_reliable_stream_buffer[BUFFER_SIZE];
    uxrStreamId reliable_out = uxr_create_output_reliable_stream(&session, output_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    uint8_t input_reliable_stream_buffer[BUFFER_SIZE];
    uxrStreamId reliable_in = uxr_create_input_reliable_stream(&session, input_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    // Create entities
    uxrObjectId participant_id = uxr_object_id(0x01, UXR_PARTICIPANT_ID);
    uint16_t participant_req = uxr_buffer_create_participant_xml(&session, reliable_out, participant_id, 0, participant_xml, UXR_REPLACE);

    uxrObjectId topic_id = uxr_object_id(0x01, UXR_TOPIC_ID);
    uint16_t topic_req = uxr_buffer_create_topic_xml(&session, reliable_out, topic_id, participant_id, topic_xml, UXR_REPLACE);

    uxrObjectId subscriber_id = uxr_object_id(0x01, UXR_SUBSCRIBER_ID);
    uint16_t subscriber_req = uxr_buffer_create_subscriber_xml(&session, reliable_out, subscriber_id, participant_id, subscriber_xml, UXR_REPLACE);

    uxrObjectId datareader_id = uxr_object_id(0x01, UXR_DATAREADER_ID);
    uint16_t datareader_req = uxr_buffer_create_datareader_xml(&session, reliable_out, datareader_id, subscriber_id, datareader_xml, UXR_REPLACE);

    // Send create entities message and wait its status
    uint8_t status[4];
    uint16_t requests[4] = {participant_req, topic_req, subscriber_req, datareader_req};
    if(!uxr_run_session_until_all_status(&session, 1000, requests, status, 4))
    {
        printf("Error at create entities: participant: %i topic: %i subscriber: %i datareader: %i\n", status[0], status[1], status[2], status[3]);
        return 1;
    }

    // Request topics
    uxrDeliveryControl delivery_control = {0};
    delivery_control.max_samples = UXR_MAX_SAMPLES_UNLIMITED;
    uint16_t read_data_req = uxr_buffer_request_data(&session, reliable_out, datareader_id, reliable_in, &delivery_control);

    // Read topics
    while(true)
    {
        uint8_t read_data_status;
        (void) uxr_run_session_until_all_status(&session, UXR_TIMEOUT_INF, &read_data_req, &read_data_status, 1);
    }

    // Delete resources
    uxr_delete_session(&session);

    return 0;
}

